# version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.2
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka_net
    deploy:
      placement:
        constraints:
          - node.hostname == nodo-manager
    volumes: 
       - zookeeper-data:/var/lib/zookeeper/data
       - zookeeper-logs:/var/lib/zookeeper/log

  broker_temis1:
    image: confluentinc/cp-server:7.6.2
    hostname: broker_temis1
    container_name: broker_temis1
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker_temis1:29092,PLAINTEXT_HOST://172.29.62.3:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'true'
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: 'true'
    depends_on:
      - zookeeper   
    networks:
      - kafka_net
    deploy:
      placement:
        constraints:
          - node.hostname == nodo1
    volumes: 
       - broker_temis1-data:/var/lib/kafka/data 

  broker_temis2:
    image: confluentinc/cp-server:7.6.2
    hostname: broker_temis2
    container_name: broker_temis2
    ports:
      - "29093:29093"
      - "9093:9093"
      - "9102:9102"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker_temis2:29093,PLAINTEXT_HOST://172.29.62.4:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9102
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'true'
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: 'true'
    depends_on:
      - zookeeper
      - broker_temis1
    networks:
      - kafka_net
    deploy:
      placement:
        constraints:
          - node.hostname == nodo2
    volumes: 
       - broker_temis2-data:/var/lib/kafka/data

  broker_temis3:
    image: confluentinc/cp-server:7.6.2
    hostname: broker_temis3
    container_name: broker_temis3
    ports:
      - "29094:29094"
      - "9094:9094"
      - "9103:9103"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker_temis3:29094,PLAINTEXT_HOST://172.29.62.5:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9103
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'true'
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: 'true'
    depends_on:
      - zookeeper
      - broker_temis1
      - broker_temis2
    networks:
      - kafka_net
    deploy:
      placement:
        constraints:
          - node.hostname == nodo3
    volumes: 
       - broker_temis3-data:/var/lib/kafka/data

  schema-registry:
    image: confluentinc/cp-schema-registry:7.7.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - broker_temis1
      - broker_temis2
      - broker_temis3
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker_temis1:29092,broker_temis2:29093,broker_temis3:29094'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    networks:
      - kafka_net
    deploy:
      placement:
        constraints:
          - node.hostname == nodo-manager

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - broker_temis1
      - broker_temis2
      - broker_temis3
    ports:
      - 9021:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker_temis1:29092,broker_temis2:29093,broker_temis3:29094
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - kafka_net
    deploy:
      placement:
        constraints:
          - node.hostname == nodo-manager

  rest-proxy:
    image: confluentinc/cp-kafka-rest:7.6.2
    depends_on:
      - broker_temis1
      - broker_temis2
      - broker_temis3
      - schema-registry
    ports:
      - 8082:8082
    hostname: rest-proxy
    container_name: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker_temis1:29092,broker_temis2:29093,broker_temis3:29094'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
    networks:
      - kafka_net
    deploy:
      placement:
        constraints:
          - node.hostname == nodo-manager

volumes:
  zookeeper-data:
  zookeeper-logs:
  broker_temis1-data:
  broker_temis2-data:
  broker_temis3-data:

networks:
  kafka_net:
    external: true

# networks:
#   kafka_net: 
#     driver: bridge